spring:
  redis:
    database: 0
    host: 47.98.194.41
    port: 6382
    timeout: 5000
    jedis:
      pool:
        max-active: 30
        max-wait: 15000
        max-idle: 10
        min-idle: 1
    password: Da7iloEusrNwEdvw_6382
  datasource:
    url: jdbc:mysql://47.98.59.188:3306/work?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: lagou
    password: lagou
